In [13]:
import pandas as pd

### Data Exploration

In [28]:
train_df = pd.read_csv('train.csv')
train_df.head(3)

,Page_traffic,Unit_price,Units_sold,Segment,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,...,Sum of Spend,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline,Units_sold>1000
0,3260.0,24.703605,1498,Makeup,82.0,64.0,180.0,353.0,1859.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,3729.0,22.226514,1139,Makeup,31.0,15.0,41.0,42.0,180.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,2675.0,25.574468,1269,Makeup,19.0,14.0,37.0,54.0,269.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [29]:
val_df = pd.read_csv('validation.csv')
val_df.head(3)

,Page_traffic,Unit_price,Units_sold,Segment,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,...,Sum of Spend,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline,Units_sold>1000
0,3046.0,22.430288,416,Hair Care,46.0,41.0,102.0,200.0,1248.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0,0
1,6452.0,20.758466,1565,Makeup,59.0,43.0,78.0,163.0,950.0,16.0,...,0.0,0.0,0.000000,0.0,0.0,6375.0,77040.81,7539723.0,2.0,1
2,4666.0,25.025785,892,Skincare,112.0,88.0,274.0,529.0,3619.0,12.0,...,0.0,948.0,2993.821631,146428.0,4.0,0.0,0.00,0.0,0.0,0

In [30]:
train_df = train_df.drop('Units_sold>1000', axis=1)
train_df.head()

,Page_traffic,Unit_price,Units_sold,Segment,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,...,Num_of_Promotions,Sum of Spend,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline
0,3260.0,24.703605,1498,Makeup,82.0,64.0,180.0,353.0,1859.0,11.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,3729.0,22.226514,1139,Makeup,31.0,15.0,41.0,42.0,180.0,8.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,2675.0,25.574468,1269,Makeup,19.0,14.0,37.0,54.0,269.0,9.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,6281.0,20.971065,1728,Makeup,25.0,18.0,62.0,107.0,532.0,0.0,...,1.0,408.036474,917.0,2654.489552,133688.0,4.0,5744.0,63978.2,6594469.0,2.0
4,131.0,20.099526,0,Skincare,23.0,21.0,45.0,91.0,559.0,16.0,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
val_df = val_df.drop('Units_sold>1000', axis=1)
val_df.head()

,Page_traffic,Unit_price,Units_sold,Segment,1_Star_Rating,2_Star_Rating,3_Star_Rating,4_Star_Rating,5_Star_Rating,Image_Count,...,Num_of_Promotions,Sum of Spend,Online_Clicks,Online_Cost,Online_Impressions,num_unique_campaigns,Clicks_video,Cost_video,Impressions_video,num_unique_campaigns_offline
0,3046.0,22.430288,416,Hair Care,46.0,41.0,102.0,200.0,1248.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0
1,6452.0,20.758466,1565,Makeup,59.0,43.0,78.0,163.0,950.0,16.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,6375.0,77040.81,7539723.0,2.0
2,4666.0,25.025785,892,Skincare,112.0,88.0,274.0,529.0,3619.0,12.0,...,0.0,0.0,948.0,2993.821631,146428.0,4.0,0.0,0.00,0.0,0.0
3,1733.0,31.328486,1169,Hair Care,72.0,54.0,97.0,250.0,1652.0,11.0,...,0.0,0.0,711.0,2241.699378,147418.0,2.0,0.0,0.00,0.0,0.0
4,4658.0,13.746230,1923,Hair Care,0.0,0.0,0.0,0.0,0.0,7.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00,0.0,0.0

In [34]:
#Storing the ratio in a list named Rating_ratio
Rating_ratio = []
for row in train_df.values:
    if(row[4]+row[5] == 0):
        if(row[7]+row[8] == 0):
            #If all the ratings are zero then overall rating ratio will also be zero
            Rating_ratio.append(0.0)
        else:
            #If only the numerator(1 and 2 star) ratings are zero then add -99999 to the list temporarily which 
            #will be taken care of in the next part of the code
            Rating_ratio.append(-99999)
    else:
        Rating_ratio.append((int(row[7])+int(row[8]))/(int(row[5])+int(row[4])));
              

#replacing -99999 with the maximum rating in the list
max_rating = max(Rating_ratio)
for x in range(len(Rating_ratio)):
    if(Rating_ratio[x] == -99999):
        Rating_ratio[x] = max_rating

#adding the column 'Good_By_Bad_Rating' to the dataframe
train_df['Good_By_Bad_Rating'] = Rating_ratio

#drop the rating columns
train_df.drop(columns = ['1_Star_Rating', '2_Star_Rating', '3_Star_Rating', '4_Star_Rating', '5_Star_Rating'], inplace = True)

#check the dataset
train_df.head().transpose()

,0,1,2,3,4
Page_traffic,3260.0,3729.0,2675.0,6281.0,131.0
Unit_price,24.703605,22.226514,25.574468,20.971065,20.099526
Units_sold,1498,1139,1269,1728,0
Segment,Makeup,Makeup,Makeup,Makeup,Skincare
Image_Count,11.0,8.0,9.0,0.0,16.0
Bullet_Count,6.0,8.0,8.0,6.0,7.0
Title_Count,67.0,126.0,126.0,77.0,140.0
Description_Length,125.0,221.0,221.0,98.0,139.0
num_unique_Search_Terms,5.0,10.0,0.0,3.0,0.0
Organic Search Rank,4.0,22.0,29.0,18.0,18.0
Num_of_Promotions,0.0,0.0,0.0,1.0,0.0
Sum of Spend,0.0,0.0,0.0,408.036474,0.0
Online_Clicks,0.0,0.0,0.0,917.0,0.0
Online_Cost,0.0,0.0,0.0,2654.489552,0.0
Online_Impressions,0.0,0.0,0.0,133688.0,0.0
num_unique_campaigns,0.0,0.0,0.0,4.0,0.0
Clicks_video,0.0,0.0,0.0,5744.0,0.0
Cost_video,0.0,0.0,0.0,63978.2,0.0
Impressions_video,0.0,0.0,0.0,6594469.0,0.0
num_unique_campaigns_offline,0.0,0.0,0.0,2.0,0.0
Good_By_Bad_Rating,15.150685,4.826087,9.787879,14.860465,14.772727

In [35]:
#Storing the ratio in a list named Rating_ratio
Rating_ratio = []
for row in val_df.values:
    if(row[4]+row[5] == 0):
        if(row[7]+row[8] == 0):
            #If all the ratings are zero then overall rating ratio will also be zero
            Rating_ratio.append(0.0)
        else:
            #If only the numerator(1 and 2 star) ratings are zero then add -99999 to the list temporarily which 
            #will be taken care of in the next part of the code
            Rating_ratio.append(-99999)
    else:
        Rating_ratio.append((int(row[7])+int(row[8]))/(int(row[5])+int(row[4])));
              

#replacing -99999 with the maximum rating in the list
max_rating = max(Rating_ratio)
for x in range(len(Rating_ratio)):
    if(Rating_ratio[x] == -99999):
        Rating_ratio[x] = max_rating

#adding the column 'Good_By_Bad_Rating' to the dataframe
val_df['Good_By_Bad_Rating'] = Rating_ratio

#drop the rating columns
val_df.drop(columns = ['1_Star_Rating', '2_Star_Rating', '3_Star_Rating', '4_Star_Rating', '5_Star_Rating'], inplace = True)

#check the dataset
val_df.head().transpose()

,0,1,2,3,4
Page_traffic,3046.0,6452.0,4666.0,1733.0,4658.0
Unit_price,22.430288,20.758466,25.025785,31.328486,13.74623
Units_sold,416,1565,892,1169,1923
Segment,Hair Care,Makeup,Skincare,Hair Care,Hair Care
Image_Count,0.0,16.0,12.0,11.0,7.0
Bullet_Count,6.0,8.0,6.0,6.0,5.0
Title_Count,81.0,162.0,92.0,93.0,84.0
Description_Length,105.0,158.0,184.0,61.0,58.0
num_unique_Search_Terms,0.0,5.0,9.0,4.0,0.0
Organic Search Rank,23.0,37.0,24.0,32.0,18.0
Num_of_Promotions,0.0,0.0,0.0,0.0,0.0
Sum of Spend,0.0,0.0,0.0,0.0,0.0
Online_Clicks,0.0,0.0,948.0,711.0,0.0
Online_Cost,0.0,0.0,2993.821631,2241.699378,0.0
Online_Impressions,0.0,0.0,146428.0,147418.0,0.0
num_unique_campaigns,0.0,0.0,4.0,2.0,0.0
Clicks_video,0.0,6375.0,0.0,0.0,0.0
Cost_video,0.0,77040.81,0.0,0.0,0.0
Impressions_video,0.0,7539723.0,0.0,0.0,0.0
num_unique_campaigns_offline,0.0,2.0,0.0,0.0,0.0
Good_By_Bad_Rating,16.643678,10.911765,20.74,15.095238,0.0

### Encoding Categorical variables

In [36]:
#one-hot encoding
train_df = pd.get_dummies(train_df, columns = ['Segment'], prefix = 'Segment', drop_first = True)
val_df = pd.get_dummies(val_df, columns = ['Segment'], prefix = 'Segment', drop_first = True)

In [37]:
from sklearn.model_selection import train_test_split

y_train = train_df['Units_sold']
X_train = train_df.drop('Units_sold', axis=1)

In [38]:
y_validation = val_df['Units_sold']
X_validation = val_df.drop('Units_sold', axis=1)

#### Run all the cells above to complete the data preprocessing and set the dependent and independent variables

## Lets try Gradient Boosting to see if it performs better

In [60]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
# Create a Gradient Boosting regressor
gradient_boosting_regressor = GradientBoostingRegressor(random_state=42)

# Fit the Gradient Boosting regressor on the training data
gradient_boosting_regressor.fit(X_train, y_train)

In [64]:
# Predict on the validation data
predictions_train = gradient_boosting_regressor.predict(X_train)
predictions_val = gradient_boosting_regressor.predict(X_validation)

r2_gb_train = r2_score(y_train, predictions_train)
print(f"R2 Score on Training Data: {round(r2_gb_train*100, 2)}%")

r2_gb_val = r2_score(y_validation, predictions_val)
print(f"R2 Score on Validation Data: {round(r2_gb_val*100, 2)}%")

R2 Score on Training Data: 63.37%
R2 Score on Validation Data: 61.45%

In [67]:
# Create a Gradient Boosting regressor
gradient_boosting_regressor = GradientBoostingRegressor(max_depth=9, min_samples_leaf=30,
    n_estimators=50, random_state=42)

# Fit the Gradient Boosting regressor on the training data
gradient_boosting_regressor.fit(X_train, y_train)

GradientBoostingRegressor(max_depth=9, min_samples_leaf=30, n_estimators=50,
                          random_state=42)

In [68]:
# Predict on the validation data
predictions_train = gradient_boosting_regressor.predict(X_train)
predictions_val = gradient_boosting_regressor.predict(X_validation)

r2_gb_train = r2_score(y_train, predictions_train)
print(f"R2 Score on Training Data: {round(r2_gb_train*100, 2)}%")

r2_gb_val = r2_score(y_validation, predictions_val)
print(f"R2 Score on Validation Data: {round(r2_gb_val*100, 2)}%")

R2 Score on Training Data: 84.3%
R2 Score on Validation Data: 77.02%